twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        bugsnag_api_key: '%env(BUGSNAG_KEY)%'
        bugsnag_release_stage: '%env(BUGSNAG_STAGE)%'

when@test:
    twig:
        strict_variables: true
