version: '3.7'

volumes:
    builder-data: {}

services:
    php-base:
        build: services/php-base

    builder:
        build: services/builder
        depends_on:
            - redis
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
            - PHP_CS_FIXER_IGNORE_ENV=1
        volumes:
            - "../../${PROJECT_DIRECTORY}:/home/app/application:cached"
            - "${COMPOSER_CACHE_DIR}:/home/app/.composer/cache"
            - "builder-data:/home/app"
