name: CI

'on':
    push:
        branches:
            - main
    pull_request: null
    schedule:
        -
            cron: '0 0 * * MON'

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            -
                uses: actions/checkout@v3

            # Setup

            -
                uses: actions/setup-python@v2
                with:
                    python-version: '3.9'
            -
                run: 'pip3 install pipenv'

            # Install the stack and run the tests

            -
                run: 'pipenv install --deploy --dev'
            -
                run: 'pipenv run inv start && sleep 5'
            -
                run: 'pipenv run inv tests'
            -
                run: 'pipenv run inv phpstan'
            -
                run: 'pipenv run inv cs --dry-run'
